# Generated by Django 2.0.3 on 2018-03-13 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aion', '0011_auto_20180312_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.CharField(max_length=250)),
                ('stars', models.DecimalField(decimal_places=1, max_digits=2)),
                ('product_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aion.Product')),
                ('user_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
