# Generated by Django 2.0.2 on 2018-03-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0012_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isPurchased',
            field=models.BooleanField(default=False),
        ),
    ]
