# Generated by Django 2.0.2 on 2018-03-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0014_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='date_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
