# Generated by Django 2.0.2 on 2018-03-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0015_auto_20180315_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_modified',
        ),
    ]
