# Generated by Django 2.0.2 on 2018-03-15 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0016_remove_cart_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
