# Generated by Django 2.0.2 on 2018-03-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0018_cart_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='commentText',
            field=models.TextField(default=''),
        ),
    ]
