# Generated by Django 2.0 on 2018-03-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0021_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session',
            field=models.CharField(max_length=200),
        ),
    ]
