# Generated by Django 2.0 on 2018-03-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0022_auto_20180326_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='session',
            new_name='session_id',
        ),
    ]
