# Generated by Django 2.0 on 2018-03-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0023_auto_20180326_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
