# Generated by Django 2.0 on 2018-04-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0025_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='location',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='result',
            field=models.CharField(default='success', max_length=30),
            preserve_default=False,
        ),
    ]
