# Generated by Django 2.0.2 on 2018-04-15 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0027_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user_details',
            name='time_created',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
