# Generated by Django 2.0.2 on 2018-04-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0028_auto_20180415_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='isTemporary',
            field=models.BooleanField(default=False),
        ),
    ]
