# Generated by Django 2.0 on 2018-04-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0029_user_details_istemporary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='middle_name',
        ),
    ]
